on:
    workflow_dispatch:

jobs:
    hybrid-job:
        runs-on: ubuntu-latest
        steps:
        - name: Run a command in Ubuntu VM
          run: echo "This is running on Ubuntu VM"

        - name: Run inside an alpine Container-docker
          uses: docker://alpine:3.14
          with:
            entrypoint: /bin/sh
            args:
              -c "echo 'This is running inside an Alpine container'"
        - name: Run another command in Ubuntu VM
          run: echo "Bach to the VM"

    dockerized-job:
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/my-org/my-private-image:latest
            credentials:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
        steps:
          - run: node --version
          - run: echo "This is running inside a Node.js container"