on:
    workflow_dispatch:
jobs:
  commands-job:
    runs-on: ubuntu-latest
    steps:
    - run: |
        deprecated=true 
        if [[ deprecated ]]; then
          echo "::warning::This command deprecated fond."
        fi 
