on:
    workflow_dispatch:
jobs:
  expression-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print a message
        run: echo "The job is running"
        if: ${{ github.event_name == 'push' }}